s/disasyncoro/netpycos/g
s/discoro/dispycos/g
s/Discoro/Dispycos/g
s/asyncoro/pycos/g
s/AsynCoro/Pycos/g
s/AsynCoroSocket/AsyncSocket/g
s/coroutine/task/g
s/Coroutine/Task/g
s/RCI/RTI/g
s/rci/rti/g
s/coro/task/g
s/Coro/Task/g
